##支付记录表
CREATE TABLE `pay_order_info` (
  `series` bigint(20) NOT NULL,
  `tenant_num_id` bigint(20) DEFAULT NULL COMMENT '租户号',
  `merchant_id` bigint(20) DEFAULT NULL COMMENT '商户号',
  `sub_unit_num_id` bigint(20) DEFAULT NULL COMMENT '门店号',
  `plat_type` int(4) DEFAULT NULL COMMENT '支付渠道: 1微信 2支付宝 3预付卡',
  `out_trade_no` varchar(40) DEFAULT '' COMMENT '订单号(包括消费和退货)',
  `request_no` varchar(40) DEFAULT '' COMMENT '请求编号防重',
  `transaction_id` varchar(100) DEFAULT NULL COMMENT '第三方支付订单流水号',
  `total_fee` float(8,2) DEFAULT NULL COMMENT '发生金额',
  `trade_status` varchar(40) DEFAULT '' COMMENT '订单状态 1：成功 2 : 超时  11：支付中 5：撤销成功 6：全部退款成功 7：部分退款 9：预付款成功 10：退款失败 -97：支付错误 -98：未支付 -99：未知错误 -100：订单不存在',
  `trade_type` tinyint(4) unsigned DEFAULT NULL COMMENT '1 支付 2 退款',
  `device_info` varchar(40) DEFAULT NULL COMMENT '设备号',
  `close_sign` tinyint(4) DEFAULT '0',
  `create_dtme` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '请求时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user_id` bigint(10) DEFAULT NULL,
  `data_sign` tinyint(4) DEFAULT '0' COMMENT '0：正式  1：测试',
  `item_body` varchar(255) DEFAULT NULL COMMENT '订单描述',
  `openid` varchar(128) DEFAULT NULL,
  `attach` varchar(2000) DEFAULT NULL,
  `cancel_sign` tinyint(4) unsigned DEFAULT '0',
  `subject` varchar(256) DEFAULT NULL COMMENT '订单标题',
  `pay_app_key` varchar(32) DEFAULT NULL,
  `create_ip` varchar(255) DEFAULT NULL,
  `trade_status_res` varchar(4000) DEFAULT NULL COMMENT '第三方支付平台返回结果',
  `channel` varchar(40) DEFAULT NULL COMMENT '来源渠道 ',
  `txndate` varchar(8) DEFAULT NULL COMMENT '交易日期 格式:YYMMDD',
  `txntime` varchar(8) DEFAULT NULL COMMENT '支付产生的时间 格式:HHMMSS',
  `tranId` varchar(5000) DEFAULT NULL COMMENT '第三方支付条码号',
  `ext1` varchar(100) DEFAULT NULL COMMENT '备用1',
  `ext2` varchar(100) DEFAULT NULL COMMENT '备用2',
  `ext3` varchar(200) DEFAULT NULL COMMENT '备用3',
  `ext4` varchar(200) DEFAULT NULL COMMENT '备用4',
  `src_out_trade_no` varchar(40) DEFAULT '' COMMENT '原订单号(退货)',
  `business_callback` varchar(200) DEFAULT '' COMMENT '业务回调url或method',
  `business_callback_status` tinyint(4) DEFAULT NULL COMMENT '业务回调状态，0 未回调，1 已回调',
  PRIMARY KEY (`series`),
  KEY `idx_tenant_num_id_out_trade_no` (`tenant_num_id`,`out_trade_no`) USING BTREE,
  KEY `idx_create_dtme` (`create_dtme`),
  KEY `uniq_out_trade_no_plat_type` (`out_trade_no`,`plat_type`),
  KEY `idx_pay_order_info_busi_call` (`trade_status`,`business_callback_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

##请求参数表
CREATE TABLE `pay_param_log` (
  `series` bigint(20) NOT NULL DEFAULT '0' COMMENT '序号（主键）',
  `out_trade_no` varchar(40) DEFAULT ' ' COMMENT '订单',
  `request_params` text COMMENT '请求参数',
  `response_params` text COMMENT '相应参数',
  `channel` varchar(40) DEFAULT ' ' COMMENT '请求渠道',
  `request_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '请求时间',
  `response_date` datetime DEFAULT NULL COMMENT '响应时间',
  `response_code` varchar(40) DEFAULT ' ' COMMENT '系统返回值',
  `response_msg` varchar(200) DEFAULT ' ' COMMENT '系统返回消息',
  `thread_id` varchar(40) DEFAULT ' ' COMMENT '线程ID',
  `ip` varchar(40) DEFAULT NULL COMMENT '处理服务器的IP',
  `tenant_num_id` bigint(20) DEFAULT '0' COMMENT '租户ID',
  `plat_type` smallint(6) DEFAULT '0',
  `operat_type` varchar(40) DEFAULT '',
  `pay_app_key` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`series`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;